# Generated by Django 2.2.1 on 2019-05-31 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(default='/user_images/no-pics.jpg', upload_to='user_images/')),
                ('status', models.CharField(default='my status', max_length=255)),
                ('online_status', models.BooleanField(default=False)),
                ('city', models.CharField(default='My city', max_length=45)),
                ('marrige', models.CharField(default='Single', max_length=45)),
                ('phone', models.IntegerField(default=1111111111)),
                ('skype', models.CharField(default='my skype', max_length=45)),
                ('school', models.CharField(default='my school', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(related_name='_users_friends_+', to='vk_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_where_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_posts_on_my_wall', to='vk_app.users')),
                ('user_who_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_created_posts', to='vk_app.users')),
                ('users_who_liked', models.ManyToManyField(related_name='liked_posts', to='vk_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('was_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_from', to='vk_app.users')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_to', to='vk_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/user_images/no-pics.jpg', upload_to='user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vk_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('profile_image', models.ImageField(default='/login_app/images/no-pics.jpg', upload_to='user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_who_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='vk_app.users')),
                ('users', models.ManyToManyField(related_name='my_groups', to='vk_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_comments', to='vk_app.Posts')),
                ('user_who_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comments', to='vk_app.users')),
                ('users_who_liked', models.ManyToManyField(related_name='liked_comments', to='vk_app.users')),
            ],
        ),
    ]
